config/routes.rb
Madloba::Application.routes.draw do

  devise_for :user, path: 'user', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'new' },
             controllers: { registrations: 'user/registrations'}

  # Home page
  get 'home/index'
  post 'search', to: 'home#render_search_results'
  get 'results', to: 'home#results'
  get 'refine_state', to: 'home#refine_state'

  # About page
  get 'about', to: 'home#about'

  # Setup pages
  get 'setup/language', to: 'setup#show_choose_language'
  post 'setup/language/process', to: 'setup#process_chosen_language'
  get 'setup', to: 'setup#show_welcome'
  get 'setup/general', to: 'setup#show_general'
  post 'setup/general/process', to: 'setup#process_general'
  get 'setup/map', to: 'setup#show_map'
  post 'setup/map/process', to: 'setup#process_map'
  get 'setup/image', to: 'setup#show_image'
  post 'setup/image/process', to: 'setup#process_image'
  get 'setup/admin', to: 'setup#show_admin'
  post 'setup/admin/process', to: 'setup#process_admin'
  get 'setup/done', to: 'setup#show_finish'

  # Redirection to custom error screens
  match '/404' => 'errors#error404', via: [ :get, :post, :patch, :delete ]
  match '/500' => 'errors#error500', via: [ :get, :post, :patch, :delete ]

  namespace :user do
    get '/', to: 'admin_panel#index'

    resources :locations, :categories, :items, :users
    resources :posts, :only => [:edit, :update, :destroy]

    get 'index', 'home', to: 'admin_panel#index'
    get 'managerecords', to: 'admin_panel#managerecords'
    get 'manageusers', to: 'admin_panel#manageusers'
    get 'manageposts', to: 'admin_panel#manageposts'
    get 'manageprofile', to: 'users#edit'
    get 'generalsettings', to: 'admin_panel#general_settings'
    get 'mapsettings', to: 'admin_panel#map_settings'
    get 'areasettings', to: 'admin_panel#area_settings'

    post 'mapsettings/update', to: 'admin_panel#update_map_settings'
    post 'generalsettings/update', to: 'admin_panel#update_general_settings'
    post 'areasettings/update', to: 'admin_panel#update_area_settings'
    post 'areasettings/update_areas', to: 'admin_panel#update_areas'
    post 'areasettings/update_area_name', to: 'admin_panel#update_area_name'
    post 'areasettings/save_area', to: 'admin_panel#save_area'
    post 'areasettings/delete_area', to: 'admin_panel#delete_area'

    get 'posts/:id/edit', to: 'posts#edit'

    # This POST method is called when the deletion of a category is made through a form
    post 'categories/:id', to: 'categories#destroy'
  end

  resources :posts, :only => [:show, :index, :new, :create], :controller => 'user/posts'
  post 'posts/send_message', to: 'user/posts#send_message'

  # Ajax calls to get details about a location (geocodes, exact address)
  get '/getNominatimLocationResponses', to: 'application#nominatim_location_responses'
  get '/retrieve_geocodes', to: 'user/locations#retrieve_geocodes'

  # Ajax call to get the list of items, for autocomplete, when searching for an item, or creating/editing a post.
  get '/getItems', to: 'application#get_items'

  # Ajax call to show the posts related to 1 type of item and to 1 area/area.
  get '/showSpecificPosts', to: 'home#showSpecificPosts'

  # Ajax call to show popup content, when marker clicked on home page.
  get '/showPostPopup', to: 'home#show_post_popup'
  get '/showAreaPopup', to: 'home#show_area_popup'

  # Root
  root 'home#index'

end

app/views/shared/_flash_messages.html.haml
- if flash[:page_error]
  .box-content.alerts
    .alert.alert-danger
      %button.close{"data-dismiss" => "alert", :type => "button"} ×
      = flash[:page_error]
- if flash[:success]
  .box-content.alerts
    .alert.alert-success
      %button.close{"data-dismiss" => "alert", :type => "button"} ×
      = flash[:success]

app/views/shared/_footer.html.haml
- footer_class = admin_panel? ? 'admin' : 'regular'
- if !current_page?(root_url)
  %footer#footer{class: footer_class}
    .container-fluid
      - if setup_mode?
        / Footer for setup pages
        %p.muted.footer-message= t('home.footer_new_powered_by_html', madloba_link: (link_to 'Madloba', 'http://madloba.org', target: '_blank'))
      - else
        / Footer for regular and admin pages
        %p.muted.footer-message
          = site_name
          \- #{t('home.footer_powered_by_html', madloba_link: (link_to 'Madloba', 'http://madloba.org', target: '_blank'))}

app/views/shared/_included_leafletdraw_scripts.haml
/ Javascript and CSS files to be included to draw polygon on a map (area settings page)
= javascript_include_tag 'draw/Toolbar'
= javascript_include_tag 'draw/Tooltip'
= javascript_include_tag 'draw/ext/GeometryUtil'
= javascript_include_tag 'draw/ext/LatLngUtil'
= javascript_include_tag 'draw/ext/LineUtil.Intersect'
= javascript_include_tag 'draw/ext/Polyline.Intersect'
= javascript_include_tag 'draw/ext/Polygon.Intersect'
= javascript_include_tag 'draw/draw/DrawToolbar'
= javascript_include_tag 'draw/draw/handler/Draw.Feature'
= javascript_include_tag 'draw/draw/handler/Draw.Polyline'
= javascript_include_tag 'draw/draw/handler/Draw.Polygon'
= javascript_include_tag 'draw/edit/EditToolbar'
= javascript_include_tag 'draw/edit/handler/EditToolbar.Edit'
= javascript_include_tag 'draw/edit/handler/EditToolbar.Delete'
= javascript_include_tag 'draw/Control.Draw'
= javascript_include_tag 'draw/edit/handler/Edit.Poly'

app/views/shared/_item_fields.html.haml
%div
  %i= t('post.write_new_item')
.nested-fields{:style => "display:inline-flex;"}
  = f.text_field :name, class: 'form-control post_item post-create-item-field'
  = f.select :category_id, options_from_collection_for_select(Category.all, :id, :name), {}, {class: 'selectpicker post-select-category form-control', data: {header: t('post.select_category') }}

app/views/shared/_links.haml
- if controller_name != 'sessions'
  = link_to t('home.sign_in').capitalize, new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to t('registration.sign_up'), new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to t('session.forgot'), new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to t('registration.not_received'), new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to t('session.not_received_unlock'), new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to t('session.sign_in_with', name: provider.to_s.titleize ), omniauth_authorize_path(resource_name, provider)
    %br/

app/views/shared/_location_form.html.haml
.nested-fields.location-fields{:style => "padding-bottom: 10px;"}

  .form-group
    %hr/
  .form-group
    .col-lg-4
      %h4= t('location.new_location')

    - if current_user.present? && current_user.locations.any? && %w(new create edit update).include?(action_name) && !@is_location_edit
      -# if the user is not anonymous and has created locations in the past, then give the possibility
      -# to remove the whole "new location" section to choose an existing location
      .col-lg-4{style: "line-height: 40px;"}
        %a.btn.btn-danger.btn-sm.remove-new-location{style: 'float: right;'}
          = t('post.choose_existing')

  -# Location name
  .form-group
    = form.label :name, t('location.name'), class: 'col-lg-2 control-label'
    .col-lg-6
      = form.text_field :name, class: 'form-control help-message', maxlength:'90', |
        :data => {:content => t('location.name_help'),                             |
        :placement => 'top', :toggle => 'popover', :trigger => 'hover focus'}      |

  -# "Give full address" / "Choose area only" radio buttons
  - if Area.any?
    .form-group
      = label_tag 'loc_type', t('location.definition'), class: 'col-lg-2 control-label'
      .col-lg-6
        .radio
          %label
            = radio_button_tag 'loc_type', 'exact', true, class: 'location_type_exact'
            = t('location.definition_exact')
        .radio
          %label
            = radio_button_tag 'loc_type', 'area', false, class: 'location_type_area'
            = t('location.definition_area')

        .why-choose-section
          %a#why_choose_link{href: '#'}= t('location.why_choose_location_type')

  .exact_location_section
    -# Street number
    .form-group
      = form.label :street_number, t('location.street_number'), class: 'col-lg-2 control-label'
      .col-lg-2
        = form.text_field :street_number, class: 'form-control location_streetnumber', maxlength:'6'

    -# Street name
    .form-group
      = form.label :address, t('location.street_name'), class: 'col-lg-2 control-label'
      .col-lg-6
        = form.text_field :address, class: 'form-control help-message location_streetname', maxlength:'90', |
          :data => {:content => t('location.street_name_help'),                                             |
          :placement => 'top', :toggle => 'popover', :trigger => 'hover focus'}

    -# Postal code
    .form-group
      = form.label :postal_code, t('location.postal_code'), class: 'col-lg-2 control-label'
      .col-lg-3
        = form.text_field :postal_code, class: 'form-control location_postal_code', maxlength:'8'

  -# Geocode (latitude and longitude hidden fields)
  = form.hidden_field :latitude, value: @map_settings[:latitude], class: 'latitude'
  = form.hidden_field :longitude, value: @map_settings[:longitude], class: 'longitude'

  -# List of area ('area' type address only)
  - if Area.any?
    #area_section
      .form-group
        = form.label :area_id, t('location.area'), class: 'col-lg-2 control-label'
        .col-lg-3
          - area_data = areas.map{|a| [a.name, a.id, { 'data-latitude' => a.latitude, 'data-longitude' => a.longitude }]}
          = form.select :area_id, options_for_select(area_data, form.object.area_id), {include_blank: t('location.area_blank')}, {class: 'form-control help-message area-select',
            :data => {:content => t('location.area_help'), :placement => 'top',
            :toggle => 'popover', :trigger => 'hover focus'}}

  -# "Locate me on the map" button
  .exact_location_section
    .form-group
      .col-lg-2.control-label
      .col-lg-8
        %a#find_geocodes_from_address.btn.btn-info{"data-content" => "#{t('home.click_on_map_after')}", "data-placement" => "right", "data-toggle" => "popover", "data-trigger" => "hover"}
          = t('location.define_geocode_button')
        %span#find_geocode_loader


  -# Canvas for the map
  .form-group
    = form.label 'map-canvas-wrapper', t('location.map'), class: 'col-lg-2 control-label'
    .col-lg-10
      #map_notification_exact.map_notification
        %i= t('admin.location.map_notification_exact')

      #map.large

  -# Phone number
  .form-group
    = form.label :phone_number, t('location.phone_number'), class: 'col-lg-2 control-label'
    .col-lg-3
      = form.text_field :phone_number, class: 'form-control', maxlength:'15'

  -# Website
  .form-group
    = form.label :website, t('location.website'), class: 'col-lg-2 control-label'
    .col-lg-4
      = form.text_field :website, class: 'form-control', maxlength:'60'

  -# Description
  .form-group
    = form.label :description, t('post.location_description'), class: 'col-lg-2 control-label'
    .col-lg-6
      = form.text_area :description, class: 'help-message', cols: 40, rows: 6, |
        :data => {:content => t('location.description_help'),                  |
        :placement => 'top', :toggle => 'popover', :trigger => 'hover focus'}  |

  - if current_user
    = form.hidden_field :user_id, value: current_user.id


#why_choose_modal.modal.fade{'aria-hidden' => 'true', 'aria-labelledby' => 'myModalLabel', :role => 'dialog', :tabindex => '-1'}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"} ×
        %h3
          = t('location.modal_exact_area_title')
      .modal-body
        %p
          = t('location.modal_exact_area_description', def_exact: t('location.definition_exact'))
          = t('location.modal_exact_area_description2')

        %p
          = t('location.modal_exact_area_description3')
          = t('location.modal_exact_area_description4', def_area: t('location.definition_area'))

      .modal-footer
        %a.btn.btn-default{"data-dismiss" => "modal", :href => "#"}= 'OK'

app/views/shared/_map_scripts.html.haml
- if MapTile.mapquest.api_key.present?
  %script{src: MapTile.mapquest.url_builder, type: 'application/javascript'}

:javascript
  // Initializing a bunch of variables used over the map-related scripts.
  var map_settings = #{raw @map_settings.to_json};
  var area_marker = "#{asset_url 'madloba_logo_green_40.png'}";

  if ($("#map").length > 0){
    initLeafletMap(map_settings);
  }

app/views/shared/_navigation.html.haml
%div{:class => "#{admin_panel? ? 'navbar' : 'navbar-inverse'} navbar-fixed-top navbar-default nav-margin-bottom", :role => "navigation"}
  .navbar-header
    %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", :type => "button"}
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    = link_to "#{image_tag madloba_logo_file_name, class: 'madloba-img'} #{navigation_madloba_title}".html_safe, navigation_madloba_icon_path, class: 'navbar-brand'
          
  - if !setup_mode?
    #navbarCollapse.navbar-collapse.collapse.navbar-responsive-collapse

      .nav-form-center
        -# Search form - start
        = form_tag root_url, {id: 'nav_search_form', class: 'navbar-form', method: 'get', role: 'search'} do
          .form-group
            = select_tag :q, options_for_select([[t('home.searching'),'searching'], [t('home.giving'),'giving']], params['q']), class: 'form-control selectpicker'
          .form-group
            = text_field_tag :item, params[:item], class:'typeahead form-control', placeholder: t('home.search_items')
          .form-group
            = text_field_tag :location,'', class:'form-control', placeholder: t('home.location_example')
          .form-group
            = submit_tag(t('home.search'), id: 'btn_form_search', class: 'btn btn-default', name: nil)
          .form-group
            %span#search_error_message{:style => "color: #d9534f; margin-left: 5px;"}
        -# Search form - end

        %ul.nav.navbar-nav.navbar-right
          -# Sign in/Register/User drop down menu - start
          - if user_signed_in?
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                %i.glyphicon.glyphicon-user
                = current_user.first_name
                %b.caret
              %ul.dropdown-menu
                - if admin_panel?
                  %li= link_to t('home.page'), root_path
                - elsif current_user.user?
                  %li= link_to t('home.user_panel'), user_index_path
                - elsif current_user.admin?
                  %li= link_to t('home.admin_panel').capitalize, user_index_path
                %li= link_to t('home.log_out'), destroy_user_session_path, method: :delete
          - else
            %li
              %a#popover{:href => "#"}= t('home.sign_register')
              #popover-content.hide.popover-larger
                = form_for(resource, as: resource_name, url: session_path(resource_name), :html => {:class => 'form-horizontal'}) do |f|
                  = t('home.e-mail')
                  %br
                  = f.email_field :email, {size: 30}
                  %br
                  = t('home.password')
                  %br
                  = f.password_field :password, {size: 30}
                  %br
                  = f.submit t('home.sign_in').capitalize, class: 'btn btn-primary btn-xs', style: 'margin-top: 5px'
                  %br
                  %br
                  = t('home.not_have_account_yet_html', sign_up_here: "#{link_to t('home.sign_up'), new_registration_path(resource_name)}".html_safe )
                  %br
                  - if demo?
                    %br/
                    %span{:style => "font-size: 12px;"}
                      %i= t('home.demo_instructions_html', here: link_to(t('post.here'), 'https://github.com/etiennebaque/madloba/wiki/Madloba-demo-instructions', target: '_blank') )
        -# Sign in/Register/User drop down menu - end


      -# In admin panel, show admin actions in collapsed menu.
      - if admin_panel?
        %ul.nav.navbar-nav
          %li.hidden-md.hidden-lg= link_to t('admin.dashboard'), user_index_path
          - if current_user.admin?
            %li.hidden-md.hidden-lg= link_to t('admin.manage_records'), user_managerecords_path
            %li.hidden-md.hidden-lg= link_to t('admin.left_menu.manage_users'), user_manageusers_path
            %li.hidden-md.hidden-lg.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                = t('admin.settings_menu')
                %b.caret
              %ul.dropdown-menu
                %li= link_to t('admin.general_settings_menu'), user_generalsettings_path
                %li= link_to t('admin.left_menu.map_settings'), user_mapsettings_path
                %li= link_to t('admin.left_menu.area_settings'), user_areasettings_path
          %li.hidden-md.hidden-lg= link_to t('admin.manage_your_posts'), user_manageposts_path
          %li.hidden-md.hidden-lg= link_to t('admin.left_menu.manage_profile'), user_manageprofile_path

  - else
    -# Setup pages - display the current step
    - if @current_step && @current_step > 0
      %span.navbar-brand= t('setup.step_html', current_step: @current_step)

- if admin_panel?
  -# Rendering admin panel, its second navigation bar and its footer in a 'ch-container' div
  = render 'shared/navigation_admin'

-# Modal popup that appears with OpenStreetMap address suggestions
#basicModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "basicModal", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %h4#myModalLabel.modal-title= t('home.refine_location')
      #modal-body-id.modal-body
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"}= t('home.cancel')

- content_for :scripts do
  :javascript
    var navigation = new NavigationBar();

app/views/shared/_navigation_admin.html.haml
%div{class: "navbar navbar-fixed-top navbar-default nav-margin-bottom admin-link-bar", role: "navigation"}
  #navbarCollapse.navbar-collapse.collapse.navbar-responsive-collapse.navbar-collapse-admin
    %ul.nav.navbar-nav.admin_link
      %li= link_to t('admin.dashboard'), user_index_path
      - if current_user.admin?
        %li= link_to t('admin.manage_records'), user_managerecords_path
        %li= link_to t('admin.left_menu.manage_users'), user_manageusers_path
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            = t('admin.settings_menu')
            %b.caret
          %ul.dropdown-menu
            %li= link_to t('admin.general_settings_menu'), user_generalsettings_path
            %li= link_to t('admin.left_menu.map_settings'), user_mapsettings_path
            %li= link_to t('admin.left_menu.area_settings'), user_areasettings_path
      %li= link_to t('admin.manage_your_posts'), user_manageposts_path
      %li= link_to t('admin.left_menu.manage_profile'), user_manageprofile_path

app/views/shared/_post_item_fields.html.haml
/ Item drop-down box and "Create a new item" button, in create/edit post page
.nested-fields.post-item-fields{:style => "padding-bottom: 10px;"}
  .item_from_list{:style => "display: inline;"}
    = f.select :item_id, options_from_collection_for_select(Item.where(id: f.object.item_id), 'id', 'name'), {}, {class: 'post-item-select-list selectpicker selectpicker-items', data: {live_search: 'true'}}
  = link_to_add_association t('post.create_item'), f, :item, partial: 'shared/item_fields', class: 'btn btn-sm btn-info post-create-item'
  = link_to_remove_association '<i class="glyphicon glyphicon-remove" style="color: red;"></i>'.html_safe, f, class: 'vert-align'

app/views/shared/_post_summary.html.haml
-# Left-hand side: Items
.show_post_paragraph
  %label
    = "#{@post.action}: "
  %span
    = @post.item_list

-# Left-hand side: Location
.show_post_paragraph
  %label= t('location.location')+':'
  %span= @post.location.full_address

-# Left-hand side: Phone number
- if @post.location.phone_number.present?
  .show_post_paragraph
    %label= t('location.phone_number')
    %span= @post.location.phone_number

-# Left-hand side: Website
- if @post.location.website.present?
  .show_post_paragraph
    %label= t('post.location_website')
    %span
      %a{:href => "#{@post.location.full_website_url}", :target => "_blank"}= @post.location.website

-# Location description
- if @post.location.description.present?
  .show_post_paragraph
    %label= t('post.location_description')
    %span= simple_format(@post.location.description)

-# Post description
.show_post_paragraph
  %label
    = t('post.description')
    \:
  %span= simple_format(@post.description)

app/views/shared/_posts_send_message.html.haml
/ 'Send message' text area
- if !is_owning(post)
  .col-lg-12.post-paragraph{:xmlns => "http://www.w3.org/1999/html"}
    / Send message to the post publisher
    = form_tag '/posts/send_message', {class:'form-horizontal'} do
      = hidden_field_tag 'id', post.id
      %fieldset
        .form-group{:style => "margin-left: 0px;"}
          = label_tag :title, t('post.send_message_label', name: publisher_name(post)), class: 'control-label'
        - if !user_signed_in?
          .form-group
            = label_tag 'name', t('post.name'), class: 'col-lg-2 control-label'
            .col-lg-4
              = text_field_tag 'name', params['name'], class: 'form-control', required: true
          .form-group
            = label_tag 'email', t('post.your_email')+'*:', class: 'col-lg-2 control-label'
            .col-lg-4
              = email_field_tag 'email', params['email'], class: 'form-control', required: true
          / Captcha for anonymous user
          .form-group
            = label_tag 'captcha', t('post.captcha'), class: 'col-lg-2 control-label'
            .col-lg-5
              = show_simple_captcha
        .form-group
          = label_tag 'message', t('post.your_message'), class: 'col-lg-2 control-label'
          .col-lg-6
            = text_area_tag 'message', params['message'], rows: 8, class: 'form-control', style: 'padding-bottom: 20px;'
      .form-actions
        .col-lg-8{:style => "text-align: right;"}
          = submit_tag(t('post.send_message'), class: 'btn btn-success')

app/views/shared/_submit_section.html.haml
/ Submit button
.form-actions
  = submit_tag(t('admin.save'), class: 'btn btn-success')
  - if current_user.admin?
    %a.btn{:href => "/user/managerecords"}= t('home.cancel')
  - else
    %a.btn{:href => "/user/manageposts"}= t('home.cancel')