config/routes.rb
Madloba::Application.routes.draw do

  devise_for :user, path: 'user', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'new' },
             controllers: { registrations: 'user/registrations'}

  # Home page
  get 'home/index'
  post 'search', to: 'home#render_search_results'
  get 'results', to: 'home#results'
  get 'refine_state', to: 'home#refine_state'

  # About page
  get 'about', to: 'home#about'

  # Setup pages
  get 'setup/language', to: 'setup#show_choose_language'
  post 'setup/language/process', to: 'setup#process_chosen_language'
  get 'setup', to: 'setup#show_welcome'
  get 'setup/general', to: 'setup#show_general'
  post 'setup/general/process', to: 'setup#process_general'
  get 'setup/map', to: 'setup#show_map'
  post 'setup/map/process', to: 'setup#process_map'
  get 'setup/image', to: 'setup#show_image'
  post 'setup/image/process', to: 'setup#process_image'
  get 'setup/admin', to: 'setup#show_admin'
  post 'setup/admin/process', to: 'setup#process_admin'
  get 'setup/done', to: 'setup#show_finish'

  # Redirection to custom error screens
  match '/404' => 'errors#error404', via: [ :get, :post, :patch, :delete ]
  match '/500' => 'errors#error500', via: [ :get, :post, :patch, :delete ]

  namespace :user do
    get '/', to: 'admin_panel#index'

    resources :locations, :categories, :items, :users
    resources :posts, :only => [:edit, :update, :destroy]

    get 'index', 'home', to: 'admin_panel#index'
    get 'managerecords', to: 'admin_panel#managerecords'
    get 'manageusers', to: 'admin_panel#manageusers'
    get 'manageposts', to: 'admin_panel#manageposts'
    get 'manageprofile', to: 'users#edit'
    get 'generalsettings', to: 'admin_panel#general_settings'
    get 'mapsettings', to: 'admin_panel#map_settings'
    get 'areasettings', to: 'admin_panel#area_settings'

    post 'mapsettings/update', to: 'admin_panel#update_map_settings'
    post 'generalsettings/update', to: 'admin_panel#update_general_settings'
    post 'areasettings/update', to: 'admin_panel#update_area_settings'
    post 'areasettings/update_areas', to: 'admin_panel#update_areas'
    post 'areasettings/update_area_name', to: 'admin_panel#update_area_name'
    post 'areasettings/save_area', to: 'admin_panel#save_area'
    post 'areasettings/delete_area', to: 'admin_panel#delete_area'

    get 'posts/:id/edit', to: 'posts#edit'

    # This POST method is called when the deletion of a category is made through a form
    post 'categories/:id', to: 'categories#destroy'
  end

  resources :posts, :only => [:show, :index, :new, :create], :controller => 'user/posts'
  post 'posts/send_message', to: 'user/posts#send_message'

  # Ajax calls to get details about a location (geocodes, exact address)
  get '/getNominatimLocationResponses', to: 'application#nominatim_location_responses'
  get '/retrieve_geocodes', to: 'user/locations#retrieve_geocodes'

  # Ajax call to get the list of items, for autocomplete, when searching for an item, or creating/editing a post.
  get '/getItems', to: 'application#get_items'

  # Ajax call to show the posts related to 1 type of item and to 1 area/area.
  get '/showSpecificPosts', to: 'home#showSpecificPosts'

  # Ajax call to show popup content, when marker clicked on home page.
  get '/showPostPopup', to: 'home#show_post_popup'
  get '/showAreaPopup', to: 'home#show_area_popup'

  # Root
  root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include ApplicationHelper

  # --------------------------------------
  # Method for the main screen (home page)
  # --------------------------------------
  def index
    # Initializing the map, in relation to its center, defined in the settings table.
    @map_settings = MapInfo.new.to_hash

    # Initializing links, and social media information, for the footer of the home page.
    settings = get_footer_info

    # Get items that match the wildcard search
    selected_item_ids = matching_items_for(params)

    if (params[:lat] && params[:lon])
        # The center of the map is now represented by the searched location.
        @map_settings[:latitude] = params[:lat]
        @map_settings[:longitude] = params[:lon]

        current_location, popup_html = current_location_for(params)
        @map_settings[:searched_address] = popup_html
        @location_search_refinement_to_display = current_location
    end

    # Defining all the categories attached to an item.
    if selected_item_ids
      # We select here only the categories, based on the items found after a search.
      @categories = Category.joins(posts: :items).where("items.id IN (?)", selected_item_ids).order('name asc').uniq
    else
      # We select the categories related to all available items
      @categories = Category.joins(posts: :items).order('name asc').uniq
    end

    # Queries to get posts to be displayed on the map, based on their locations
    search_result_objects(params, selected_item_ids)
  end


  # -------------------------
  # Method for the About page
  # -------------------------
  def about
    settings = Setting.where(key: %w(contact_email description))
    settings.each do |setting|
      if setting['key'] == 'description' && setting['value'] != ''
        @website_description_paragraph = setting['value'].split(/[\r\n]+/)
      end
      if setting['key'] == 'contact_email' && setting['value'] != ''
        @contact_email = setting['value']
      end
    end

    render 'home/about'
  end

  # ------------------
  # Search result page
  # ------------------
  def results
    id = params[:area].to_i
    @posts = Post.includes(:location, :items).where(locations: {area_id: id})
               .paginate(page: params[:page] || 1, per_page: 10 )

    @area = Area.find(id)
    render 'home/results'
  end

  # Method called when marker on the home page is clicked.
  # Returns the HTML code that will create the popup linked to that marker.
  def show_post_popup
    render json: MarkerPopup.post_popup_for(params['post_id'])
  end

  # Same as above, but when area marker is clicked.
  def show_area_popup
    render json: MarkerPopup.area_popup_for(params['area_id'])
  end

  # From the home page, based on the selected navigation, get the relevant posts.
  def refine_state
    markers, post_results = post_markers_and_results_for(params)
    render json: {markers: markers}
  end

  # Method that gets markers and search results list, after a search is made on home page
  def render_search_results
    results = ''
    markers, post_results = post_markers_and_results_for(params)
    post_results.each do |post|
      results += Result.create(post)
    end

    areas = []
    markers.each do |marker|
      if marker['area'] > 0
        areas << marker['area']
        markers.delete(marker)
      end
    end

    selected_areas = Area.where(id: areas.uniq).select(:id, :name, :latitude, :longitude)

    render json: {markers: markers, areas: selected_areas, results: results, categories: post_results.map{|p| p.category_id.to_s}.uniq}
  end

  private

  def post_markers_and_results_for(params)
    selected_item_ids = matching_items_for(params)
    post_results = Post.search(params, selected_item_ids, nil)
    markers = post_results.pluck(:marker_info).uniq
    [markers, post_results]
  end

  def matching_items_for(params)
    if params[:item].present?
      selected_item_ids = Item.joins(:posts).where('name LIKE ?', "%#{params[:item].downcase}%").pluck(:id).uniq
    end
    selected_item_ids
  end

  def search_result_objects(params, selected_item_ids)
    # Get the posts tied to an exact location.
    @post_results = Post.search(params, selected_item_ids, nil)
    @locations_exact = @post_results.pluck(:marker_info).uniq

    # Getting a hash that matches areas to their respective latitude and longitudes.
    @areas = Area.all.select(:id, :name, :latitude, :longitude)

    @url_params = {}
    @url_params[:q] = params[:q] if params[:q].present?
    @url_params[:item] = params[:item] if params[:item].present?
  end

  def current_location_for(params)
    # A location search was just performed, with the name of the searched location (given back from Nominatim ws) in it.
    return [params[:loc], MarkerPopup.location_popup_for(params[:loc])] if params.has_key?(:loc)

    # there was no search beforehand, we need to find the address, based on given latitude and longitude.
    current_location = address_from_geocodes(params[:lat], params[:lon])
    current_location = t('home.default_current_loc') if current_location.blank?

    [current_location, MarkerPopup.location_popup_for(current_location)]
  end

  # Creates a hash with the link and the label of one "Useful link",
  # that appears at the center of the home page footer.
  def get_link(label, url)
    if label != '' && url != ''
      return {label: label, url: url}
    end
  end

  # Get information ready for the footer of the home page
  # (eg. Website description, contact email, social media links... )
  # Also returns a settings hash, that will be needed for the rest of HomeController#index execution.
  def get_footer_info
    settings = {}
    Setting.all.each do |setting|
      settings[setting['key']]=setting['value']
    end

    # Useful links, for the footer section.
    link_numbers = %w(one two three four)
    @links = []
    link_numbers.each do |number|
      @links << get_link(settings["link_#{number}_label"], settings["link_#{number}_url"])
    end
    settings
  end

end

app/helpers/home_helper.rb
module HomeHelper

  # Devise resources related methods
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/views/home/_search_result_sidebar.html.haml
- currently_querying = @url_params[:item].present? && @post_results.present?
#search_result.sidebar.sidebar-right.collapsed.hide
  -# Nav tabs
  .sidebar-tabs
    %ul{role: 'tablist'}
      %li
        %a{href: '#results', role: 'tab', style: 'font-size: 20px'}
          %i.fa.fa-search#search_result_icon

  -# Tab panes
  .sidebar-content.search-content
    -# Search results
    #results.sidebar-pane.search-panes
      %h1.sidebar-header
        = 'Results'
        %span.sidebar-close
          %i.fa.fa-caret-right

      #result_list.list-group.results
        - if currently_querying
          - @post_results.each do |post|
            .result
              .post-title= link_to post.title, post
              .post-address
                %i.fa{class: post.location.area? ? Location::AREA_ADDRESS_ICON : Location::EXACT_ADDRESS_ICON}
                = post.location.full_address

              .post-items= "#{post.action} #{post.item_list}".html_safe
              .post-description= post.short_description

app/views/home/_sidebar.html.haml
- website_description = Setting.description
#sidebar.sidebar.sidebar-left.collapsed
  -# Nav tabs
  .sidebar-tabs
    %ul{role: 'tablist'}
      %li
        %a.sidebar-icon{href: '#category', role: 'tab', style: 'font-size: 20px'}
          %i.fa.fa-map-marker#sidebar_category_icon
      - if website_description.present?
        %li
          %a.sidebar-icon{href: '#about', role: 'tab'}
            %i.fa.fa-info
      %li
        %a.sidebar-icon{href: '#contact', role: 'tab'}
          %i.fa.fa-envelope

  -# Tab panes
  .sidebar-content

    -# Categories
    #category.sidebar-pane
      %h1.sidebar-header
        = site_city
        %span.sidebar-close
          %i.fa.fa-caret-left

      .inner-section
        .list-group.create-post
          %a.btn.btn-success.no-color{:href => "/posts/new"}
            %i.fa.fa-plus
            %span
              = t('home.create_new_post')

        -# Area drop down
        .list-group
          - if @areas.any?
            - select_options = {class: 'form-control area-select',
                                include_blank: '-- Move to area --'}
            - area_data = @areas.map{|a| [a.name, a.id, { 'data-latitude' => a.latitude, 'data-longitude' => a.longitude }]}
            = select_tag 'area', options_for_select(area_data), select_options

        .list-group
          - if @location_search_refinement_to_display.present?
            %h4= t('home.your_searched_location')
            %a.list-group-item.smaller-no-border-no-background{:href => "/"}
              %span= params[:loc]
              %i.glyphicon.glyphicon-remove.align-cross{:style => "float: right"}

          .searching-giving
            -# "You're searching for: / You're giving away:" refinement
            %h5.searching.hide= t('home.searching_for')
            %h5.giving.hide= t('home.giving_away')
            %a.queried-item.list-group-item.smaller-no-border-no-background.hide{:href => "/"}
              %span= params[:item].try(:capitalize)
              %i.glyphicon.glyphicon-remove.align-cross{:style => "float: right"}

        -# List of selected categories
        #refinements
          - @categories.each do |category|
            - if category.is_refinement(params)
              %a.list-group-item.smaller-no-border-no-background.guided-nav-category{:href => "#{category.refinement_url(params)}"}
                %label{:style => "width: 15px;"}
                  %i{:class => "fa #{category.icon}", :style => "color: #{category.marker_color_hexacode};"}
                %span.guided-nav-label= category.name
                %i.glyphicon.glyphicon-remove.align-cross{:style => "float: right"}

        -# Sidebar - list of Categories
        .list-group
          - if @categories.any?
            %h5= t('admin.categories')
            #available_categories
              - @categories.each do |category|
                - if !category.is_refinement(params)
                  %a.list-group-item.smaller-no-border-no-background.guided-nav-category{:href => "#", :id => "#{category.id}"}
                    %label{:style => "width: 15px;"}
                      %i{:class => "fa #{category.icon}", :style => "color: #{category.marker_color_hexacode};"}
                    %span.guided-nav-label= category.name

          - else
            .list-group
              .list-group-item.smaller-no-border-no-background
                %p= t('home.no_post')
                %p= t('home.create_an_post_now_html', create_new_post: (link_to t('home.create_new_post'), new_post_url) )


        -# Sidebar - note with some explanation, for demo only
        - if demo?
          %hr/
          .list-group
            %i= t('home.demo_sidebar_note_html', admin_panel: link_to(t('home.admin_panel'), '/user/managerecords#categories'))


    -# Contact us
    #contact.sidebar-pane
      %h1.sidebar-header
        Contact us
        %span.sidebar-close
          %i.fa.fa-caret-left

      .inner-section
        - contact_email = Setting.contact_email
        - social_medias = Setting.social_medias
        - if contact_email.present?
          .send-us-message
            %p= t('home.send_us_message')
            %p= link_to contact_email.value, "mailto:#{contact_email.value}"

        - if social_medias.any?
          .social_media
            %p
              - social_medias.each do |media|
                = link_to image_tag("#{media.key}.png", size: '40x40'), media.url, target: '_blank'

    -# About us
    - if website_description.present?
      #about.sidebar-pane
        %h1.sidebar-header
          About us
          %span.sidebar-close
            %i.fa.fa-caret-left

        .inner-section
          - website_description.each do |descr|
            %p= descr

          - if @links.any?
            %hr
            %p= 'More information:'
            %ul
              - @links.each do |link|
                - if link && link[:label] && link[:label] != ''
                  %li
                    %a{:href => "#{link[:url]}"}= link[:label]

- content_for :scripts do
  :javascript
    var sidebar = new Sidebar();

app/views/home/about.html.haml
.container
  .row
    .col-lg-12
      %div{:style => "padding-bottom: 30px"}
        %h3= t('home.about_page', website_name: site_name)
      .col-lg-12
        / Website description paragraph - to be set in admin panel -> 'General Settings'
        - if @website_description_paragraph
          %div
            - @website_description_paragraph.each do |paragraph|
              %p= paragraph
          %hr/
        / General description
        %div
          %p
            = t('home.about_description_1_html', website_name: site_name, madloba_link: link_to('Madloba', 'http://madloba.org', target: '_blank'))
          %p
            = t('home.about_description_2_html', madloba_link: link_to('Madloba', 'http://madloba.org', target: '_blank'))
          %p
            = t('home.about_description_3')
        / Contact e-mail address
        - if @contact_email
          %hr/
          %div
            %p= t('home.about_send_message_html', email: (link_to @contact_email, "mailto:#{@contact_email}"))

app/views/home/index.html.haml
-# Sidebar
= render 'sidebar'

-# Search result sidebar
= render 'search_result_sidebar'


-# Map
#map.home.sidebar-map


-# Loading JS scripts
- content_for :scripts do

  -# Includes all the Javascript related to map rendering, to be loaded after page
  -# (Leaflet, MapQuest, and script that creates the actual map)
  = render 'shared/map_scripts', include_all_scripts: false

  -# Javascript function calls, related specifically to the home page
  :javascript
    // specific script to render map markers and initialize the sidebar.
    var locations_exact = #{raw @locations_exact.to_json}
    var areas = #{raw @areas.to_json};
    var params = #{raw @url_params.to_json};
    var marker_colors = #{raw MARKER_COLORS.to_json};

    var homePage = new Home(locations_exact, areas, params, marker_colors);

app/views/home/results.html.haml
.container#results_page
  .col-xs-12.col-md-offset-2.col-md-8

    .summary
      = t('results.title', area: @area.name, num: @posts.count)

    %hr

    .results
      - @posts.each do |post|
        .result
          .post-title= link_to post.title, post
          .post-address
            %i.fa{class: post.location.area? ? Location::AREA_ADDRESS_ICON : Location::EXACT_ADDRESS_ICON}
            = post.location.full_address

          .post-items= "#{post.action} #{post.item_list}".html_safe
          .post-description= post.short_description

    .madloba-pagination
      = will_paginate @posts, container: false