config/routes.rb
Madloba::Application.routes.draw do

  devise_for :user, path: 'user', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'new' },
             controllers: { registrations: 'user/registrations'}

  # Home page
  get 'home/index'
  post 'search', to: 'home#render_search_results'
  get 'results', to: 'home#results'
  get 'refine_state', to: 'home#refine_state'

  # About page
  get 'about', to: 'home#about'

  # Setup pages
  get 'setup/language', to: 'setup#show_choose_language'
  post 'setup/language/process', to: 'setup#process_chosen_language'
  get 'setup', to: 'setup#show_welcome'
  get 'setup/general', to: 'setup#show_general'
  post 'setup/general/process', to: 'setup#process_general'
  get 'setup/map', to: 'setup#show_map'
  post 'setup/map/process', to: 'setup#process_map'
  get 'setup/image', to: 'setup#show_image'
  post 'setup/image/process', to: 'setup#process_image'
  get 'setup/admin', to: 'setup#show_admin'
  post 'setup/admin/process', to: 'setup#process_admin'
  get 'setup/done', to: 'setup#show_finish'

  # Redirection to custom error screens
  match '/404' => 'errors#error404', via: [ :get, :post, :patch, :delete ]
  match '/500' => 'errors#error500', via: [ :get, :post, :patch, :delete ]

  namespace :user do
    get '/', to: 'admin_panel#index'

    resources :locations, :categories, :items, :users
    resources :posts, :only => [:edit, :update, :destroy]

    get 'index', 'home', to: 'admin_panel#index'
    get 'managerecords', to: 'admin_panel#managerecords'
    get 'manageusers', to: 'admin_panel#manageusers'
    get 'manageposts', to: 'admin_panel#manageposts'
    get 'manageprofile', to: 'users#edit'
    get 'generalsettings', to: 'admin_panel#general_settings'
    get 'mapsettings', to: 'admin_panel#map_settings'
    get 'areasettings', to: 'admin_panel#area_settings'

    post 'mapsettings/update', to: 'admin_panel#update_map_settings'
    post 'generalsettings/update', to: 'admin_panel#update_general_settings'
    post 'areasettings/update', to: 'admin_panel#update_area_settings'
    post 'areasettings/update_areas', to: 'admin_panel#update_areas'
    post 'areasettings/update_area_name', to: 'admin_panel#update_area_name'
    post 'areasettings/save_area', to: 'admin_panel#save_area'
    post 'areasettings/delete_area', to: 'admin_panel#delete_area'

    get 'posts/:id/edit', to: 'posts#edit'

    # This POST method is called when the deletion of a category is made through a form
    post 'categories/:id', to: 'categories#destroy'
  end

  resources :posts, :only => [:show, :index, :new, :create], :controller => 'user/posts'
  post 'posts/send_message', to: 'user/posts#send_message'

  # Ajax calls to get details about a location (geocodes, exact address)
  get '/getNominatimLocationResponses', to: 'application#nominatim_location_responses'
  get '/retrieve_geocodes', to: 'user/locations#retrieve_geocodes'

  # Ajax call to get the list of items, for autocomplete, when searching for an item, or creating/editing a post.
  get '/getItems', to: 'application#get_items'

  # Ajax call to show the posts related to 1 type of item and to 1 area/area.
  get '/showSpecificPosts', to: 'home#showSpecificPosts'

  # Ajax call to show popup content, when marker clicked on home page.
  get '/showPostPopup', to: 'home#show_post_popup'
  get '/showAreaPopup', to: 'home#show_area_popup'

  # Root
  root 'home#index'

end

app/controllers/user/admin_panel_controller.rb
class User::AdminPanelController < ApplicationController
  before_action :authenticate_user!
  before_filter :requires_user

  include ApplicationHelper

  # Style used to display messages on 'Area settings' page
  STYLES = {success: 'text-success', error: 'text-danger' }

  def requires_user
    if !user_signed_in?
      redirect_to '/user/login'
    end
  end

  def index
    @messages = []
    if (current_user.admin?)
      # To-do list creation
      Todo.all.each do |todo|
        @messages << todo.message_and_alert if !todo.condition_met?
      end
    end
  end

  # ---------------------------------------
  # Admin: "Manage records", "Manage users"
  # ---------------------------------------
  def managerecords
    authorize :admin, :managerecords?
  end

  def manageusers
    authorize :admin, :manageusers?
  end


  # --------------------------------------
  # Methods for 'General settings' screens
  # --------------------------------------
  def general_settings_keys
    %w(app_name description contact_email post_max_expire facebook twitter pinterest
              link_one_label link_one_url link_two_label link_two_url
              link_three_label link_three_url link_four_label link_four_url)
  end

  def map_settings_keys
    %w(map_box_api_key mapquest_api_key map_center_geocode chosen_map city state country zoom_level)
  end

  def general_settings
    authorize :admin, :generalsettings?

    settings = Setting.where(key: general_settings_keys)

    @settings = {}
    settings.each do |setting|
      @settings[setting.key] = setting.value
    end

    @description_remaining = 500
    if @settings['description'] && @settings['description'].length > 0
      @description_remaining = 500 - @settings['description'].length
    end

  end

  def update_general_settings
    general_settings_keys.each do |key|
      if key == 'app_name'
        if params[key].present?
          app_name_settings = Setting.find_by_key(key)
          app_name_settings.update_attribute(:value, params[key])

          # Updating cached value.
          Rails.cache.write(CACHE_APP_NAME, params[key]) if !Rails.env.test?
        else
          # the application name has been deleted. We can't save an empty app name.
          flash[:setting_success] = 0
          break
        end
      else
        app_name_settings = Setting.find_by_key(key)
        cleaned_data = params[key]
        if %w(_url facebook pinterest).any? {|word| key.include?(word) }
          # Cleaning up the urls
          if (params[key] != '') && (!params[key].include? 'http')
            cleaned_data = "http://#{params[key]}"
          end
        elsif key == 'post_max_expire'
          Rails.cache.write(CACHE_MAX_DAYS_EXPIRE, cleaned_data)
        end
        app_name_settings.update_attribute(:value, cleaned_data)
      end
      flash[:setting_success] = 1
    end
    redirect_to user_generalsettings_path
  end


  # ----------------------------------
  # Methods for 'Map settings' screens
  # ----------------------------------
  def map_settings
    authorize :admin, :mapsettings?
    @form = MapSettingsForm.new
    @map_settings = MapInfo.new.to_hash

  end

  def update_map_settings
    @form = MapSettingsForm.new(params[:map_settings_form])
    flash[:success] = @form.submit

    redirect_to user_mapsettings_path
  end


  # -----------------------------------
  # Methods for 'Area settings' screen
  # ----------------------------------
  def area_settings
    authorize :admin, :areasettings?

    @map_settings = MapInfo.new.to_hash
  end

  def update_area_settings
    flash[:setting_success] = t('admin.map_settings.area_update_success')
    redirect_to user_areasettings_path

  end
  
  # Save/update an area after it has been drawn on a map and named, on the "Area settings" page.
  def save_area
    updating = params[:id].to_i > 0
    status = 'success'
    begin
      if updating
        # Updating an area
        Area.find(params[:id]).update_attributes(name: params[:name],
                                                 latitude: params[:latitude],
                                                 longitude: params[:longitude])
        message = t('admin.area_settings.save_name_success')
      else
        # Creation of area
        a = Area.new(name: params[:name], latitude: params[:latitude].to_f, longitude: params[:longitude].to_f)
        if a.save
          message = t("admin.area_settings.#{updating ? 'update' : 'save'}_success")
          Rails.cache.write(CACHE_AREAS, Area.select(:id, :name, :latitude, :longitude))
        else
          status = 'error'
          message = t('admin.area_settings.error_save_area')
        end
      end
    rescue Exception => e
      message = I18n.t('admin.area_settings.error_save_area')
      status = 'error'
    end

    render json: {updating: updating, message: message, style: STYLES[status.to_sym], id: a.id || 0, name: params[:name]}
  end

  # Updating the name of an existing area
  def update_area_name
    d = Area.find(params[:id].to_i)
    style, message = '', ''
    if d && d.update_attributes(name: params[:name])
      message = t('admin.area_settings.save_name_success')
      style = STYLES[:success]
      Rails.cache.write(CACHE_AREAS, Area.select(:id, :name, :bounds))
    else
      message = t('admin.area_settings.error_name_save')
      style = STYLES[:error]
    end

    render json: {'message' => message, 'style' => style}
  end   

  # Updating the boundaries of existing areas
  def update_areas
    areas = JSON.parse(params[:areas])
    style, message = '', ''
    areas.each do |area|
      # Editing an existing area at a time.
      area_id = area['properties']['id']
      area_name = area['properties']['name']
      if area_id
        area['properties'] = {}
        d = Area.find(area_id.to_i)
        if d.update_attributes(name: area_name, bounds: area.to_json)
          message = t('admin.area_settings.update_success')
          style = STYLES[:success]
          Rails.cache.write(CACHE_AREAS, Area.select(:id, :name, :bounds))
        else
          message = t('admin.area_settings.error_update_area')
          style = STYLES[:error]
          break
        end
      end
    end

    render json: {'message' => message, 'style' => style}
  end 

  # Deletes existing area
  def delete_area
    id = params[:id].to_i
    style, message = '', ''

    area = Area.find(id)
    if area.delete
      message = t('admin.area_settings.delete_success')
      style = STYLES[:success]
      Rails.cache.write(CACHE_AREAS, Area.select(:id, :name, :latitude, :longitude))
    else
      message = t('admin.area_settings.delete_error')
      style = STYLES[:error]
    end

    render json: {'message' => message, 'style' => style}
  end

  # --------------------------------
  # Methods for regular user screens
  # --------------------------------
  def manageposts
    @posts = Post.includes(:items).where(user: current_user)
    @locations = Location.where(user: current_user)
  end

  def manageprofile
    @user = current_user
  end

  private

  def social_networks
    %w(facebook twitter pinterest)
  end

end

app/controllers/user/categories_controller.rb
class User::CategoriesController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
  before_action :init_icons_to_propose
  after_action :verify_authorized
  after_action :serialize_posts, only: [:update]

  def show
    @category = Category.find(params[:id])
    authorize @category

    render 'category'
  end

  def new
    @category = Category.new
    authorize @category

    @category.icon = 'fa-circle' #default icon

    render 'category'
  end

  def create
    @category = Category.new(category_params)
    authorize @category

    if @category.save
      flash[:new_name] = @category.name
      redirect_to edit_user_category_path(@category.id)
    else
      render 'category'
    end
  end

  def edit
    @category = Category.find(params[:id])
    authorize @category

    render 'category'
  end

  def update
    @category = Category.find(params[:id])
    authorize @category

    if @category.update(category_params)
      flash[:name] = @category.name
      redirect_to edit_user_category_path
    else
      render 'category'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    authorize @category

    if params['target_category']
      # Transfer of tied items to another category, before going ahead with the deletion of this category.
      target_category = Category.find(params['target_category'])
      @category.items.each do |item|
        item.category = target_category
        item.save
      end
    end

    deleted_category_name = @category.name
    if @category.destroy
      flash[:success] = t('admin.category.success_deleted', name: deleted_category_name)
      redirect_to user_managerecords_path
    else
      @available_colors = MarkerColor.pluck(:id, :name)
      render 'category'
    end

  end

  private

  def category_params
    params.require(:category).permit(:name, :description, :icon, :marker_color)
  end

  # Updates the relevant posts marker_info (jsonb) and update the marker color and marker icon in the 'markers' nested array.
  def serialize_posts
    if @category.errors.empty?
      posts = Post.where('category_id = ?', params[:id])
      posts.each do |post|
        post.serialize!
      end
    end
  end

  def init_icons_to_propose
    count = 0
    keywords = []
    @icon_keyword_list = []
    ICON_SELECTION.each do |icon|
      keywords << icon
      count += 1
      if count == 4
        @icon_keyword_list << keywords
        count = 0
        keywords = []
      end
    end
  end

end

app/controllers/user/confirmations_controller.rb
class User::ConfirmationsController < Devise::ConfirmationsController
  def new
    super
  end
end

app/controllers/user/passwords_controller.rb
class User::PasswordsController < Devise::PasswordsController
  def new
    super
  end

  def edit
    super
  end
end

app/controllers/user/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
  def new
    super
  end

  def create
    super
  end

  def destroy
    super
  end
end

app/helpers/user/admin_panel_helper.rb
module User::AdminPanelHelper

  # On the Map Setting page, initializing the map type drop down box.
  def options_for_maptype_select(map_setting)
    options_for_maptype_select = []
    options_for_maptype_select << ['OpenStreetMap', 'open_street_map']
    # If a Mapbox and a MapQuest keys has been provided, then we include them in the drop down box
    if map_setting['map_box_api_key'] && map_setting['map_box_api_key'] != ''
      options_for_maptype_select << ['Mapbox', 'mapbox']
    end
    if map_setting['mapquest_api_key'] && map_setting['mapquest_api_key'] != ''
      options_for_maptype_select << ['MapQuest', 'mapquest']
    end

    options_for_maptype_select

  end
end

app/helpers/user/categories_helper.rb
module User::CategoriesHelper
end

app/helpers/user/confirmations_helper.rb
module User::ConfirmationsHelper
end

app/helpers/user/items_helper.rb
module User::ItemsHelper
end

app/helpers/user/location_form_helper.rb
module User::LocationFormHelper

  # Get all the areas for the location form partial.
  def areas
    Area.all.select(:id, :name, :latitude, :longitude)
  end


end

app/helpers/user/locations_helper.rb
module User::LocationsHelper

  def is_adding_new
    action_name == 'new' || action_name == 'create'
  end
end

app/helpers/user/posts_helper.rb
module User::PostsHelper

  # All items from the database, for the item field, in the New post form
  def all_items
    Item.pluck(:name)
  end

  # Checks if current user owns this post.
  def is_owning(post)
    current_user && current_user.owns_post(post)
  end

  # Checks if anonymous user who posted a post added their email address.
  # If they did, users will be able to send them a message about this post.
  def anon_user_puts_email(post)
    current_user == nil && post.anon_email != nil
  end

  # Checks if image upload is allowed
  def can_upload_image
    image_storage = Rails.cache.fetch(CACHE_IMAGE_STORAGE) {Setting.find_or_create_by(key: 'image_storage').value}
    return (image_storage == IMAGE_ON_SERVER || image_storage == IMAGE_AMAZON_S3)
  end

  def publisher_name(post)
    publisher_name = ''
    if post.is_anonymous
      publisher_name = post.anon_name
    else
      post_user = post.user
      if post.username_used?
        publisher_name = post_user.username
      else
        publisher_name = "#{post_user.first_name} #{post_user.last_name}"
      end
    end
    return publisher_name
  end

  # When a post-related page loads, the associated image might still be processed, or being uploaded to S3.
  # This method checks if the normal image is available yet.
  def is_image_available(post)
    return post.image && (post.image.versions)[:normal].file.present? && (post.image.versions)[:normal].file.exists?
  end

  # Getting the maximum number of days of publication, before post expires.
  def max_expire_days
    Setting.where(key: 'post_max_expire').pluck(:value).first
  end

  # If a signed-in user is creating a post, they will have the choice to create a new location
  # or to choose one of their existing location (registered when creating other posts before).
  def can_choose_existing_locations(current_user)
    current_user != nil && current_user.locations.length > 0
  end

  def expire_date_for(post)
    return '' if post.expire_date.to_s == '2100-01-01'

    if Date.today > post.expire_date
      I18n.t('post.has_expired', expire_date: post.expire_date.to_s)
    elsif Date.today < post.expire_date
      I18n.t('post.expiration_date', expire_date: post.expire_date.to_s)
    else
      I18n.t('post.expires_today')
    end
  end

  def expire_date_for_new_post
    max_expire_days.to_i > 0 ? t('post.once_created_expire_html', max_expire_days: max_expire_days) : ''
  end

end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/user/users/_delete_modal_window.html.haml
/ "Delete user" - modal window
#myModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"} ×
        %h3
          = t('admin.users.delete')
          ?
      .modal-body
        %p= t('admin.users.confirm_delete')
        %p= t('admin.users.confirm_delete_2')
      .modal-footer
        %a.btn.btn-default{"data-dismiss" => "modal", :href => "#"}= t('home.cancel')
        = link_to t('admin.users.delete_yes'), user_user_path(@user), method: :delete, class: 'btn btn-danger'

app/views/user/users/user.html.haml
.row
  #content.middle-col.col-xs-12.col-md-10
    / content starts
    - if @is_managing_user
      %div
        %ul.breadcrumb
          %li
            %a{:href => "/user/manageusers/"}= t('admin.profile.title_manage_users')
          - if @is_adding
            %li= t('admin.profile.new_user')
          - else
            %li= t('admin.profile.update_profile')
    .row
      .box.col-md-12
        .box-inner
          .box-header.well{"data-original-title" => ""}
            - if @is_managing_user
              - if @is_adding
                %h2
                  %i.glyphicon.glyphicon-user
                  = t('admin.profile.new_user')
              - else
                %h2
                  %i.glyphicon.glyphicon-user
                  = t('admin.profile.update_profile')
            - else
              %h2
                %i.glyphicon.glyphicon-user
                = t('admin.profile.title')
          - if @user && @user.errors.any?
            .alert.alert-danger
              %button.close{"data-dismiss" => "alert", :type => "button"} ×
              %strong
                = t('admin.users.error_occurred', errors: pluralize(@user.errors.count, t('home.error.one'), t('home.error.more')))
                \:
              %ul
                - @user.errors.full_messages.each do |msg|
                  %li= msg
          - if flash[:user]
            .alert.alert-success
              %button.close{"data-dismiss" => "alert", :type => "button"} ×
              - if current_user.admin?
                = t('admin.users.update_success', email: flash[:user])
                %a{:href => "/user/manageusers"}= t('admin.back_to_users')
              - else
                = t('admin.users.myprofile_update_success')
          - if flash[:new_user]
            .alert.alert-success
              %button.close{"data-dismiss" => "alert", :type => "button"} ×
              = t('admin.users.created_success', email: flash[:new_user])
              %a{:href => "/user/manageusers"}= t('admin.back_to_users')
          .box-content
            = form_for [:user, @user], html: { role: 'form' } do |f|
              - if current_user.admin? && !@is_adding && current_user != @user
                .form-group
                  - if demo?
                    / User deletion not allowed on demo
                    = link_to t('admin.users.delete_not_possible'), '#', class: 'btn btn-danger disabled'
                  - else
                    = link_to t('admin.users.delete'), '#', class: 'btn btn-danger btn-delete-right btn-setting'
              - if @is_adding
                .form-group
                  = t('registration.all_mandatory')
              / E-mail
              .form-group
                = f.label :email, t('home.e-mail'), class:'control-label'
                .form-inline
                  = f.email_field :email, class: 'form-control', size: '40'
              / 'Make admin' checkbox
              - if current_user.admin? && current_user != @user
                .form-group
                  .checkbox
                    %label
                      = f.check_box :role, {}, 'admin', 'user'
                      = t('admin.profile.make_user_admin')
              / First name
              .form-group
                = f.label :first_name, t('admin.profile.first_name')+':', class:'control-label'
                .form-inline
                  = f.text_field :first_name, class: 'form-control'
              / Last name
              .form-group
                = f.label :last_name, t('admin.profile.last_name')+':', class:'control-label'
                .form-inline
                  = f.text_field :last_name, class: 'form-control'
              / Username
              .form-group
                = f.label :username, t('admin.profile.username')+':', class:'control-label'
                .form-inline
                  = f.text_field :username, class: 'form-control'
              / Current password
              - if !@is_adding && !current_user.admin?
                .form-group
                  = f.label :current_password, t('admin.profile.current_password')+':', class:'control-label'
                  %i= t('registration.need_current')
                  %br/
                  .form-inline
                    = f.password_field :current_password, class: 'form-control', autocomplete: 'off'
              %hr/
              / New password
              .form-group
                = f.label :password, t('admin.profile.new_password')+':', class:'control-label'
                - if !@is_adding
                  %i= t('registration.leave_blank')
                  %br/
                .form-inline
                  = f.password_field :password, class: 'form-control', autocomplete: 'off'
              / Confirm password
              .form-group
                = f.label :password_confirmation, t('admin.profile.confirm_password')+':', class: 'control-label'
                .form-inline
                  = f.password_field :password_confirmation, class: 'form-control', autocomplete: 'off'
              - if demo? && action_name == 'edit'
                / User creation and update is not allowed on Madloba demo website
                .form-actions
                  = link_to t('admin.save_not_possible'), '#', class: 'btn btn-success disabled'
                  = link_to t('home.cancel'), '/user/index', class: 'btn'
              - else
                / Submit button and cancel link
                = render 'shared/submit_section'
    / content ends
  / /#content.span10
/ /row
- if !@is_adding
  / "Delete user" - modal window
  = render 'delete_modal_window'