config/routes.rb
Madloba::Application.routes.draw do

  devise_for :user, path: 'user', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'new' },
             controllers: { registrations: 'user/registrations'}

  # Home page
  get 'home/index'
  post 'search', to: 'home#render_search_results'
  get 'results', to: 'home#results'
  get 'refine_state', to: 'home#refine_state'

  # About page
  get 'about', to: 'home#about'

  # Setup pages
  get 'setup/language', to: 'setup#show_choose_language'
  post 'setup/language/process', to: 'setup#process_chosen_language'
  get 'setup', to: 'setup#show_welcome'
  get 'setup/general', to: 'setup#show_general'
  post 'setup/general/process', to: 'setup#process_general'
  get 'setup/map', to: 'setup#show_map'
  post 'setup/map/process', to: 'setup#process_map'
  get 'setup/image', to: 'setup#show_image'
  post 'setup/image/process', to: 'setup#process_image'
  get 'setup/admin', to: 'setup#show_admin'
  post 'setup/admin/process', to: 'setup#process_admin'
  get 'setup/done', to: 'setup#show_finish'

  # Redirection to custom error screens
  match '/404' => 'errors#error404', via: [ :get, :post, :patch, :delete ]
  match '/500' => 'errors#error500', via: [ :get, :post, :patch, :delete ]

  namespace :user do
    get '/', to: 'admin_panel#index'

    resources :locations, :categories, :items, :users
    resources :posts, :only => [:edit, :update, :destroy]

    get 'index', 'home', to: 'admin_panel#index'
    get 'managerecords', to: 'admin_panel#managerecords'
    get 'manageusers', to: 'admin_panel#manageusers'
    get 'manageposts', to: 'admin_panel#manageposts'
    get 'manageprofile', to: 'users#edit'
    get 'generalsettings', to: 'admin_panel#general_settings'
    get 'mapsettings', to: 'admin_panel#map_settings'
    get 'areasettings', to: 'admin_panel#area_settings'

    post 'mapsettings/update', to: 'admin_panel#update_map_settings'
    post 'generalsettings/update', to: 'admin_panel#update_general_settings'
    post 'areasettings/update', to: 'admin_panel#update_area_settings'
    post 'areasettings/update_areas', to: 'admin_panel#update_areas'
    post 'areasettings/update_area_name', to: 'admin_panel#update_area_name'
    post 'areasettings/save_area', to: 'admin_panel#save_area'
    post 'areasettings/delete_area', to: 'admin_panel#delete_area'

    get 'posts/:id/edit', to: 'posts#edit'

    # This POST method is called when the deletion of a category is made through a form
    post 'categories/:id', to: 'categories#destroy'
  end

  resources :posts, :only => [:show, :index, :new, :create], :controller => 'user/posts'
  post 'posts/send_message', to: 'user/posts#send_message'

  # Ajax calls to get details about a location (geocodes, exact address)
  get '/getNominatimLocationResponses', to: 'application#nominatim_location_responses'
  get '/retrieve_geocodes', to: 'user/locations#retrieve_geocodes'

  # Ajax call to get the list of items, for autocomplete, when searching for an item, or creating/editing a post.
  get '/getItems', to: 'application#get_items'

  # Ajax call to show the posts related to 1 type of item and to 1 area/area.
  get '/showSpecificPosts', to: 'home#showSpecificPosts'

  # Ajax call to show popup content, when marker clicked on home page.
  get '/showPostPopup', to: 'home#show_post_popup'
  get '/showAreaPopup', to: 'home#show_area_popup'

  # Root
  root 'home#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :post_items
  has_many :items, through: :post_items
  belongs_to :category
  belongs_to :location
  belongs_to :user

  include ApplicationHelper
  after_initialize :default_values

  # Post image
  mount_uploader :image, ImageUploader
  process_in_background :image

  accepts_nested_attributes_for :location, :reject_if => :all_blank
  accepts_nested_attributes_for :post_items, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :items

  validates_presence_of :title, :description, :category
  validates :giving, inclusion: [true, false]
  validates :username_used, inclusion: [true, false]
  validate :has_items
  validate :has_anon_name_and_email
  validates_size_of :image, maximum: 5.megabytes

  apply_simple_captcha

  # This method returns the right query to display relevant markers, on the home page.
  def self.search(params, selected_item_ids, post_id)
    return Post.find(post_id) if post_id.present?

    user_action = params[:q]
    searched_item = params[:item]
    cat_nav_state = params[:cat].present? ? params[:cat].split(" ") : []

    posts = Post.where("expire_date >= ? and (marker_info->>'post_id') is not null", Date.today).uniq

    posts = posts.joins(:items).where(items: {id: selected_item_ids}) if searched_item.present?
    posts = posts.where(category_id: cat_nav_state) if cat_nav_state.present?
    posts = posts.where(giving: user_action == 'searching') if user_action.present?

    posts
  end

  # method used to save the posts#new form. A captcha is required when the user is anonymous.
  # In that case the save method is different than the classic one.
  def save_with_or_without_captcha(current_user)
    if current_user
      self.save
    else
      self.username_used = false
      self.save_with_captcha
    end
  end

  def has_items
    errors.add(:base, I18n.t('post.error_post_must_have_item')) if (self.post_items.blank? || self.post_items.empty?)
  end

  def has_anon_name_and_email
    errors.add(:base, I18n.t('post.provide_anon_name')) if (self.user_id.nil? && self.anon_name.blank?)
    errors.add(:base, I18n.t('post.provide_anon_email')) if (self.user_id.nil? && self.anon_email.blank?)
  end

  def action
    giving? ? I18n.t('admin.post.giving_away') : I18n.t('admin.post.accepting')
  end

  def action_item
    act = giving? ? I18n.t('admin.post.giving_away') : I18n.t('admin.post.accepting')
    self.items.each do |item|

    end

    "#{act} #{self.items.map(&:name).join(', ')}"
  end

  # The publisher of a post might not want to have their full name publicly displayed.
  # This method defines whether to show the username or the full name (whether it is anonymous or registered user)
  def username_to_display
    if self.is_anonymous
      self.anon_name
    elsif self.username_used?
      self.user.username
    else
      "#{self.user.first_name} #{self.user.last_name}"
    end
  end

  # If we deal with an anonymous post publisher, we get the email from the post itself (no user model created)
  # Otherwise we get the email from the user model linked to the post.
  def email_to_display
    is_anonymous ? anon_email : user.email
  end

  def short_description
    description.length > 100 ? "#{description[0..96]}..." : description
  end


  def has_expired
    self.expire_date < Date.today
  end

  # Define whether or not this post has been created by a signed-in or an anonymous user.
  def is_anonymous
    self.user_id == nil && self.anon_name != nil
  end

  def thumb_image_url
    self.image_url(:thumb)
  end

  def recreate_delayed_versions!
    self.image.is_processing_delayed = true
    self.image.recreate_versions!
  end

  # Clean list of items linked to a post
  def item_list
    self.items.map{|i| i.name}.compact.join(', ')
  end

  # {
  #   lat: 12.23456,
  #   lng: 12.23456,
  #   area: 1
  #   post_id: 123,
  #   category_id: 2
  #   icon: 'fa-circle',
  #   color: 'blue',
  # }
  def serialize!
    location = self.location
    cat = self.category
    info = {
        lat: location.latitude,
        lng: location.longitude,
        area: location.area? ? location.area.id : 0,
        post_id: self.id
    }
    info.merge!({icon: cat.icon, color: cat.marker_color, category_id: cat.id})
    self.marker_info = info
    self.save
  end

  private

  # Setting default values after initialization.
  def default_values
    # we define the date when the post won't be published any longer (see maximum number of days, in Settings table)
    if max_number_days_publish == '0'
      # No limit set for post expiration. Let's use 2100-01-01 as a default date value
      self.expire_date = Date.new(2100,1,1)
    else
      d = Date.today
      self.expire_date = d + max_number_days_publish.to_i
    end
  end

end

app/controllers/user/categories_controller.rb
class User::CategoriesController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
  before_action :init_icons_to_propose
  after_action :verify_authorized
  after_action :serialize_posts, only: [:update]

  def show
    @category = Category.find(params[:id])
    authorize @category

    render 'category'
  end

  def new
    @category = Category.new
    authorize @category

    @category.icon = 'fa-circle' #default icon

    render 'category'
  end

  def create
    @category = Category.new(category_params)
    authorize @category

    if @category.save
      flash[:new_name] = @category.name
      redirect_to edit_user_category_path(@category.id)
    else
      render 'category'
    end
  end

  def edit
    @category = Category.find(params[:id])
    authorize @category

    render 'category'
  end

  def update
    @category = Category.find(params[:id])
    authorize @category

    if @category.update(category_params)
      flash[:name] = @category.name
      redirect_to edit_user_category_path
    else
      render 'category'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    authorize @category

    if params['target_category']
      # Transfer of tied items to another category, before going ahead with the deletion of this category.
      target_category = Category.find(params['target_category'])
      @category.items.each do |item|
        item.category = target_category
        item.save
      end
    end

    deleted_category_name = @category.name
    if @category.destroy
      flash[:success] = t('admin.category.success_deleted', name: deleted_category_name)
      redirect_to user_managerecords_path
    else
      @available_colors = MarkerColor.pluck(:id, :name)
      render 'category'
    end

  end

  private

  def category_params
    params.require(:category).permit(:name, :description, :icon, :marker_color)
  end

  # Updates the relevant posts marker_info (jsonb) and update the marker color and marker icon in the 'markers' nested array.
  def serialize_posts
    if @category.errors.empty?
      posts = Post.where('category_id = ?', params[:id])
      posts.each do |post|
        post.serialize!
      end
    end
  end

  def init_icons_to_propose
    count = 0
    keywords = []
    @icon_keyword_list = []
    ICON_SELECTION.each do |icon|
      keywords << icon
      count += 1
      if count == 4
        @icon_keyword_list << keywords
        count = 0
        keywords = []
      end
    end
  end

end

app/controllers/user/confirmations_controller.rb
class User::ConfirmationsController < Devise::ConfirmationsController
  def new
    super
  end
end

app/controllers/user/items_controller.rb
class User::ItemsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
  before_action :authenticate_user!
  before_action :requires_user
  after_action :verify_authorized
  after_action :serialize_posts, only: [:update]

  def show
    @item = Item.includes(:posts).where(id: params[:id]).first!
    authorize @item
    render 'item'
  end

  def new
    @adding = true
    @item = Item.new
    authorize @item
    render 'item'
  end

  def create
    @item = Item.new(item_params)
    authorize @item

    if @item.save
      flash[:new_name] = @item.name
      redirect_to edit_user_item_path(@item.id)
    else
      @isAdding = true
      render 'item'
    end
  end

  def edit
    @item = Item.includes(:posts).where(id: params[:id]).first!
    authorize @item
    render 'item'
  end

  def update
    @item = Item.find(params[:id])
    authorize @item

    if @item.update(item_params)
      flash[:name] = @item.name
      redirect_to edit_user_item_path
    else
      render 'item'
    end
  end

  def destroy
    @item = Item.find(params[:id])
    authorize @item
    deleted_item_name = @item.name

    if @item.destroy
      flash[:success] = t('admin.item.item_deleted', deleted_item_name: deleted_item_name)
      redirect_to user_managerecords_path
    else
      @item = Item.includes(:posts).where(id: params[:id]).first!
      render 'item'
    end

  end

  private

  def item_params
    params.require(:item).permit(:name, :category_id)
  end

  # Updates the relevant posts marker_info (jsonb) and update the category id in the 'markers' nested array.
  def serialize_posts
    if @item.errors.empty?
      posts = Post.joins(:items).where('items.id = ?', params[:id])
      posts.each do |post|
        post.serialize!
      end
    end
  end

end

app/controllers/user/passwords_controller.rb
class User::PasswordsController < Devise::PasswordsController
  def new
    super
  end

  def edit
    super
  end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  def new
    super
  end

  def update
    super
  end

  protected

  def after_inactive_sign_up_path_for(resource)
    if request.referer.include? 'setup'
      setup_done_path
    else
      root_path
    end
  end

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :username, :email, :password, :password_confirmation, :role)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :username, :email, :password, :password_confirmation, :current_password, :role)
  end

end

app/controllers/user/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
  def new
    super
  end

  def create
    super
  end

  def destroy
    super
  end
end

app/helpers/user/admin_panel_helper.rb
module User::AdminPanelHelper

  # On the Map Setting page, initializing the map type drop down box.
  def options_for_maptype_select(map_setting)
    options_for_maptype_select = []
    options_for_maptype_select << ['OpenStreetMap', 'open_street_map']
    # If a Mapbox and a MapQuest keys has been provided, then we include them in the drop down box
    if map_setting['map_box_api_key'] && map_setting['map_box_api_key'] != ''
      options_for_maptype_select << ['Mapbox', 'mapbox']
    end
    if map_setting['mapquest_api_key'] && map_setting['mapquest_api_key'] != ''
      options_for_maptype_select << ['MapQuest', 'mapquest']
    end

    options_for_maptype_select

  end
end

app/helpers/user/categories_helper.rb
module User::CategoriesHelper
end

app/helpers/user/confirmations_helper.rb
module User::ConfirmationsHelper
end

app/helpers/user/items_helper.rb
module User::ItemsHelper
end

app/helpers/user/location_form_helper.rb
module User::LocationFormHelper

  # Get all the areas for the location form partial.
  def areas
    Area.all.select(:id, :name, :latitude, :longitude)
  end


end

app/helpers/user/locations_helper.rb
module User::LocationsHelper

  def is_adding_new
    action_name == 'new' || action_name == 'create'
  end
end

app/helpers/user/posts_helper.rb
module User::PostsHelper

  # All items from the database, for the item field, in the New post form
  def all_items
    Item.pluck(:name)
  end

  # Checks if current user owns this post.
  def is_owning(post)
    current_user && current_user.owns_post(post)
  end

  # Checks if anonymous user who posted a post added their email address.
  # If they did, users will be able to send them a message about this post.
  def anon_user_puts_email(post)
    current_user == nil && post.anon_email != nil
  end

  # Checks if image upload is allowed
  def can_upload_image
    image_storage = Rails.cache.fetch(CACHE_IMAGE_STORAGE) {Setting.find_or_create_by(key: 'image_storage').value}
    return (image_storage == IMAGE_ON_SERVER || image_storage == IMAGE_AMAZON_S3)
  end

  def publisher_name(post)
    publisher_name = ''
    if post.is_anonymous
      publisher_name = post.anon_name
    else
      post_user = post.user
      if post.username_used?
        publisher_name = post_user.username
      else
        publisher_name = "#{post_user.first_name} #{post_user.last_name}"
      end
    end
    return publisher_name
  end

  # When a post-related page loads, the associated image might still be processed, or being uploaded to S3.
  # This method checks if the normal image is available yet.
  def is_image_available(post)
    return post.image && (post.image.versions)[:normal].file.present? && (post.image.versions)[:normal].file.exists?
  end

  # Getting the maximum number of days of publication, before post expires.
  def max_expire_days
    Setting.where(key: 'post_max_expire').pluck(:value).first
  end

  # If a signed-in user is creating a post, they will have the choice to create a new location
  # or to choose one of their existing location (registered when creating other posts before).
  def can_choose_existing_locations(current_user)
    current_user != nil && current_user.locations.length > 0
  end

  def expire_date_for(post)
    return '' if post.expire_date.to_s == '2100-01-01'

    if Date.today > post.expire_date
      I18n.t('post.has_expired', expire_date: post.expire_date.to_s)
    elsif Date.today < post.expire_date
      I18n.t('post.expiration_date', expire_date: post.expire_date.to_s)
    else
      I18n.t('post.expires_today')
    end
  end

  def expire_date_for_new_post
    max_expire_days.to_i > 0 ? t('post.once_created_expire_html', max_expire_days: max_expire_days) : ''
  end

end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/user/posts/_error_modal.html.haml
#myErrorModal.modal.hide.fade
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
        %h4= t('location.not_found')
      .modal-body
        %p= t('location.not_found_descr1')
        %p= t('location.not_found_descr2')
      .modal-footer
        %a.btn.btn-default{"data-dismiss" => "modal", :type => "button"} OK

app/views/user/posts/_form.html.haml
- page ||= 'new'
- obj ||= @post
= form_for obj, html: { id: 'post_form', class: 'form-horizontal', role: 'form', multipart: true } do |f|
  - note_about_expiration_date = page == 'new' ? expire_date_for_new_post: expire_date_for(@post)
  %fieldset

    - if page == 'edit'
      -# Edit page: "Delete Post" and "See published ad" buttons
      .form-group
        .col-lg-6
          %a.btn.btn-danger.btn-delete-right.btn-setting{:href => "#", :style => "margin-right: 10px;"}= t('admin.post.delete')
          = link_to t('post.see_published'), post_path(@post.id), {target: '_blank', class: 'btn btn-info'}
      %hr

    - if page == 'new'
      %h3= t('post.new_post')

    .form-group
      .col-lg-6.col-lg-offset-2
        %i= note_about_expiration_date

    -# Post title
    .form-group
      = f.label :title, t('post.title'), class: 'col-lg-2 control-label'
      .col-lg-6
        = f.text_field :title, class: 'form-control help-message', autofocus: true,
                :data => {:content => t('post.title_help'), :placement => 'top',
                :toggle => 'popover', :trigger => 'hover focus'}

    -# Name to use (it user is not anonymous)
    - if user_signed_in?
      .form-group
        = f.label :username_used, t('location.name_to_use'), class: 'col-lg-2 control-label'
        .col-lg-6
          .radio
            %label
              = f.radio_button :username_used, true, checked: true
              = t('location.name_username')
              (#{current_user.username})
          .radio
            %label
              = f.radio_button :username_used, false
              = t('location.name_fullname')
              (#{current_user.first_name} #{current_user.last_name})

    -# Category
    .form-group
      = f.label :category_id, t('post.category'), class: 'col-lg-2 control-label'
      .col-lg-3
        - category_data = Category.all.map{|c| [c.name, c.id, { 'data-color' => c.color_code, 'data-icon' => c.icon }]}
        = f.select :category_id, options_for_select(category_data, f.object.category_id), {include_blank: t('location.category_blank')}, {class: 'form-control'}

    -# Giving / Accepting items
    .form-group
      = f.label :giving, t('location.post_action'), class: 'col-lg-2 control-label'
      .col-lg-6
        .radio
          %label
            = f.radio_button :giving, true, checked: true
            = t('location.post_action_giving')
        .radio
          %label
            = f.radio_button :giving, false
            = t('location.post_action_accepting')

    -# Items
    .form-group
      = f.label :item_ids, t('post.items'), class: 'col-lg-2 control-label'
      .col-lg-6.field-for-items
        = f.text_field :item_ids, {data: {role: 'tagsinput'}}

    -# Post description
    .form-group
      = f.label :description, t('post.description')+'*:', class: 'col-lg-2 control-label'
      .col-lg-6
        = f.text_area :description, class: 'form-control help-message', rows: 6

    -# Image upload - only possible when app deployed on server, for now
    - if can_upload_image
      .form-group
        = f.label :description, t('post.upload_image'), class: 'col-lg-2 control-label'
        .col-lg-6
          = f.file_field :image, class: 'form-control', style: 'border: 0px; height: auto;'
          = f.hidden_field :image_cache
          %span#message= t('post.less_than_limit')
      .form-group
        .col-lg-2
        .col-lg-10
          #image-section
          - if @post.image?
            - if is_image_available(@post)
              = image_tag @post.image_url(:normal).to_s
              .checkbox
                %label
                  = f.check_box :remove_image
                  = t('post.remove_image')
            - elsif @post.image && (@post.errors[:image].nil? || (@post.errors[:image] && @post.errors[:image].length == 0))
              .post-processing
                = t('post.image_selected')

    -# Post location section
    - if current_user.present? && current_user.locations.any?
      -# List of all the different locations previously entered by the current user
      #locations_from_list
        .form-group
          = f.label :location_id, t('location.location')+'*:', class: 'col-lg-2 control-label'
          .col-lg-6
            - current_user.locations.each_with_index do |loc, index|
              .radio.existing_location
                %label
                  - if index == 0
                    = f.radio_button :location_id, loc.id, checked: true
                    = loc.full_address
                  - else
                    = f.radio_button :location_id, loc.id
                    = loc.full_address

        .form-group
          .col-lg-6.col-lg-offset-2
            %a.btn.btn-sm.btn-info.add-new-location
              = t('post.new_location')

    -# Location form partial
    .location-form-for-post
      = f.fields_for :location, Location.new, html: {class: 'form-horizontal'} do |loc|
        = render 'shared/location_form', form: loc, location: @post.location

    -# if anonymous user creates an ad, we need to ask for their name and email
    -# They need to provide a response to a captcha
    - if !user_signed_in?
      %h4= t('post.about_you')
      -# Anonymous user's name
      .form-group
        = f.label :anon_name, t('post.name'), class: 'col-lg-2 control-label'
        .col-lg-6
          = f.text_field :anon_name, class: 'form-control help-message',
                  :data => {:content => t('post.name_help'), :placement => 'top',
                  :toggle => 'popover', :trigger => 'hover focus'}
      -# Anonymous user's email
      .form-group
        = f.label :anon_email, t('post.your_email')+'*:', class: 'col-lg-2 control-label'
        .col-lg-6
          = f.email_field :anon_email, class: 'form-control help-message', autofocus: true,
                  :data => {:content => t('post.email_help'), :placement => 'top',
                  :toggle => 'popover', :trigger => 'hover focus'}
      -# Captcha for anonymous user
      .form-group
        = f.label :anon_captcha, t('post.captcha'), class: 'col-lg-2 control-label'
        .col-lg-6
          = f.show_simple_captcha
      %hr/

    -# Submit section
    .form-group{style: 'margin-top: 35px'}
      .col-lg-10.col-lg-offset-2
        = f.submit t("post.submit_post_#{page}"), id: 'submit_new_post', class: 'btn btn-success'
        %a.btn{:href => "/"}= t('home.cancel')

    -# After submit, a notification shows up here, if a new image is being uploaded
    .form-group
      .col-lg-10.col-lg-offset-2
        %span#upload-in-progress

app/views/user/posts/edit.html.haml
.container
  .row
    #content.middle-col.col-xs-12.col-md-10
      / content starts
      %div
        %ul.breadcrumb
          - if current_user.admin?
            %li
              %a{:href => "/user/managerecords"}= t('admin.manage_records')
          - else
            %li
              %a{:href => "/user/manageposts"}= t('admin.post.manage_posts')
          %li= t('admin.update_post')
      .row
        .box.col-md-12
          .box-inner
            .box-header.well{"data-original-title" => ""}
              %h2
                %i.glyphicon.glyphicon-edit
                = t('admin.post.post_edit')
            - if flash[:post_updated]
              .alert.alert-success
                %button.close{"data-dismiss" => "alert", :type => "button"} ×
                = t('admin.post.post_updated', title: flash[:post_updated])
                - if current_user.admin?
                  %a{:href => "/user/managerecords#posts"}= t('admin.back_to_records')
                - else
                  %a{:href => "/user/manageposts"}= t('admin.back_to_posts')
            - if flash[:error_post] || flash[:error_delete_post]
              .alert.alert-danger
                %button.close{"data-dismiss" => "alert", :type => "button"} ×
                - if @post && @post.errors.any?
                  %strong
                    = t('admin.post.error_update', errors: pluralize(@post.errors.count, t('home.error.one'), t('home.error.more')))
                    \:
                  %ul
                    - @post.errors.full_messages.each do |msg|
                      %li= msg
                - else
                  - if flash[:error_delete_post]
                    = t('admin.post.delete_post_error_html', manage_posts_page: link_to(t('admin.post.manage_posts_page'), '/user/manageposts'))

            .box-content
              = render 'user/posts/form', page: 'edit', obj: [:user, @post]


/ "Delete ad" - modal window
#myModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"} ×
        %h3= t('admin.post.delete_post')
      .modal-body
        %p= t('admin.post.delete_post_permanently')
      .modal-footer
        %a.btn.btn-default{"data-dismiss" => "modal", :href => "#"}= t('home.cancel')
        = link_to t('admin.post.delete_this_post'), user_post_path(@post), method: :delete, class: 'btn btn-danger'

/ "Location not found" - modal window
#myErrorModal.modal.hide.fade
  .modal-header
    %button.close{"data-dismiss" => "modal", :type => "button"} ×
    %h3= t('location.not_found')
  .modal-body
    %p= t('location.not_found_descr1')
    %p= t('location.not_found_descr2')
  .modal-footer
    %a.btn{"data-dismiss" => "modal", :href => "#"} OK
- content_for :scripts do
  / Includes all the Javascript related to map rendering (Leaflet, MapQuest, and script that creates the actual map
  = render 'shared/map_scripts', include_all_scripts: false

  :javascript
    adForm = new PostForm();

app/views/user/posts/new.html.haml
-# For anonymous user creating posts, we're adding a note saying that they can modify their ad, if they create an account.
- if current_user.nil?
  .col-lg-12.post-non-signed-warning.alert.alert-dismissible.alert-warning{:role => "alert"}
    %button.close{"data-dismiss" => "alert", :type => "button"} ×
    %p= t('post.create_account_first_html',                                                                                         |
        create_account: (link_to t('home.create_account').capitalize, new_registration_path(resource_name), class: 'alert-link'), |
        sign_in: (link_to t('home.sign_in'), new_session_path(resource_name), class: 'alert-link'))                               |

.container
  - if @post.errors.any?
    .alert.alert-dismissable.alert-danger{:style => "margin-top: 21px;"}
      %button.close{"data-dismiss" => "alert", :type => "button"} ×
      %strong
        = t('post.error_occurred', errors: pluralize(@post.errors.count, t('home.error.one'), t('home.error.more')))
        \:
      %ul
        - @post.errors.each do |_, msg|
          %li= msg

  .row
    .col-lg-12
      = render 'user/posts/form'
      
-# Loading JS scripts
- content_for :scripts do

  -# Includes all the Javascript related to map rendering (Leaflet, MapQuest, and script that creates the actual map
  = render 'shared/map_scripts'

  :javascript
    var location_number = #{user_locations_number};
    var canPickExistingLocs = #{can_choose_existing_locations(current_user)};
    adForm = new PostForm();